on:
  push:
    branch:
      - main

  jobs:
    maven:
      runs-on: ubuntu-24.04
      steps:
        - uses: actions/checkout@v5
        - uses: actions/setup-java@v5
          with: 
            distribution: 'temurin'
            java-version: '21'
        - run: mvn clean package  
