on:
  push:
    branches: [main]

jobs:
  maven:
      runs-on: ubuntu-24.04
      steps:
        - uses: actions/checkout@v5
        - uses: actions/setup-java@v5
          with: 
            java-version: '21'
        - run: mvn clean package  
